<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\AssemblyInfo.props" />

  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SoftWell.RtClearing.Moex</AssemblyName>
    <RootNamespace>SoftWell.RtClearing.Moex</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SoftWell.Fix.Initiator" Version="7.4.0" />
    <PackageReference Include="SoftWell.RtCodes.Abstractions" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
  </ItemGroup>

</Project>
